version: '3.8'
services:
  db:
    image: postgres:13
    ports:
      - 25433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: books
      networks:
      - cursogo
      networks:
        cursogo